PRIVATE_KEY: testonly
DEVISE_JWT_SECRET_KEY: -------
DEVELOPMENT_HOST: localhost:3000
TEST_HOST: localhost:3000
PRODUCTION_HOST: localhost:3000
EMAIL_SENDER: --------
EMAIL_SENDER_PASSWORD: -------
LOGIN_PATH: http://0.0.0.0/login
DEV_DOMAIN: www.viral-ads.com
INSTAGRAM_KEY: -----
INSTAGRAM_SECRET: --------
FACEBOOK_KEY: '------'
FACEBOOK_SECRET: ----------
APP_DOMAIN: http://0.0.0.0:8000
FRONTEND_TOKEN: "/get-token"
